// tailwind.config.ts
import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./pages/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container":         "#201f20",
        "on-surface":                "#e2e2e2",
        "tertiary":                  "#a1a1aa",
        "primary-fixed-dim":         "#10b981",
        "tertiary-fixed-dim":        "#71717a",
        "surface-container-low":     "#1c1b1c",
        "inverse-surface":           "#e2e2e2",
        "on-tertiary-container":     "#f4f4f5",
        "secondary-fixed":           "#34d399",
        "surface-container-high":    "#2c2b2c",
        "secondary-fixed-dim":       "#10b981",
        "outline":                   "#525252",
        "inverse-primary":           "#059669",
        "surface-bright":            "#3a393a",
        "on-background":             "#e2e2e2",
        "on-tertiary":               "#18181b",
        "surface-tint":              "#10b981",
        "error-container":           "#450a0a",
        "tertiary-container":        "#3f3f46",
        "surface-variant":           "#2c2b2c",
        "on-error":                  "#fecaca",
        "on-secondary-fixed-variant":"#064e3b",
        "outline-variant":           "#3a393a",
        "on-tertiary-fixed":         "#f4f4f5",
        "on-secondary-fixed":        "#022c22",
        "primary-container":         "#064e3b",
        "surface-dim":               "#131314",
        "primary-fixed":             "#6ee7b7",
        "on-primary-fixed-variant":  "#065f46",
        "on-secondary-container":    "#d1fae5",
        "primary":                   "#10b981",
        "surface-container-lowest":  "#0e0e0f",
        "on-error-container":        "#fca5a5",
        "secondary-container":       "#064e3b",
        "surface-container-highest": "#333233",
        "on-primary":                "#022c22",
        "inverse-on-surface":        "#131314",
        "on-primary-container":      "#d1fae5",
        "on-secondary":              "#022c22",
        "error":                     "#ef4444",
        "on-primary-fixed":          "#022c22",
        "secondary":                 "#10b981",
        "surface":                   "#131314",
        "on-surface-variant":        "#a1a1aa",
        "on-tertiary-fixed-variant": "#52525b",
        "background":                "#131314",
        "tertiary-fixed":            "#e4e4e7",
      },
      fontFamily: {
        sans:       ["Inter", "sans-serif"],
        mono:       ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "4px",
        lg:      "4px",
        xl:      "4px",
        full:    "9999px",
      },
    },
  },
  plugins: [],
};

export default config;