server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: nexgate-mock-backend

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.nexgate.mock: INFO
